[package]
name = "epub-zip-rs"
version = "0.1.0"
authors = ["Satoshi Kojima <skoji@skoji.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.11"
walkdir = "2"